# MySQL Database
# This plugin requires MySQL Database.
# Most server providers provide at least (1) free database, ask them to provide you one.
# --------------------------------------------------------------------------------------
mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: vlib_db